### ISSUE TITLE
Multiple sitemaps possible?

### ISSUE THREAD

**Issue by kodekoder** [nuxt-community/sitemap-module#19] opened 2018-03-15 21:01 UTC
Hello. Is it possible to create separate multiple sitemaps?
I want separate sitemap for Google News.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/sitemap-module/issues/c18">#c18</a>)</em></sub></div>

**Comment by NicoPennec** [comment] 2018-03-16 18:01
related to https://github.com/nuxt-community/sitemap-module/issues/6

@jerakode I've never met this use case with [Google News](https://support.google.com/news/publisher/answer/74288) before.
So probably we can implement this feature for a next release of the module, it seems useful!

Thanks for your feedback 👍

**Comment by jerakode** [comment] 2018-04-02 17:27
@NicoPennec this would be amazing! Would love to test it in practice!

**Comment by pSchaub** [comment] 2018-07-05 15:01
This feature would be awesome, especially for Google News.

**Comment by manniL** [comment] 2019-01-12 20:05
I guess it's a dupe of #6 :thinking:

**Closed** 2019-02-07 11:29 UTC
Labels: enhancement
