### ISSUE TITLE
404 error when I try to access .../sitemap.xml

### ISSUE THREAD

**Issue by Thyoity** [nuxt-community/sitemap-module#163] opened 2020-10-01 22:31 UTC
Every time I try to access the ...mywebsite.com/sitemap.xml in production, I get 404 error.

I have a "extendRoutes" set in my project like this:
![image](https://user-images.githubusercontent.com/10885945/94869379-a2fc3d80-041b-11eb-9623-3bd255e8150b.png)

In local, everything is working fine, but in production, the sitemap.xml is unreachable, 404 error.

Does anyone have any idea?

**Comment by febrihidayan** [comment] 2020-10-09 12:25
I have experienced the same thing as you. I myself do not understand why the production time and upload to the server all seem to fail.

#156

**Comment by larswww** [comment] 2020-10-24 08:39
I'm having the same issue. I have tried the fix suggested in the other thread. In production it's not available on /sitemap.xml nor /static/sitemap.xml. 

So I've saved it manually to my static dir and included it that way. Not ideal perhaps but works for my case currently.

What are we missing here?

**Comment by febrihidayan** [comment] 2020-10-25 04:28
Hi @larswww, Is your server.js code the same as mine? I used it like this and it worked
```js
const { loadNuxt } = require('nuxt')
const server = require("express")()

async function start() {

    // We get Nuxt instance
    const nuxt = await loadNuxt('start')

    // Render every route with Nuxt.js
    server.use(nuxt.render)
    
    // Listen the server
    server.listen()

}

start()
```

**Comment by JSAustin** [comment] 2020-11-09 00:56
Hello, I am having this same issue, I think. When I run locally (either dev or build/start), I can access the sitemap at sitemap.xml. However, when I deploy online (using ElasticBeanstalk via CodeDeploy), I get a 404 trying to visit the /sitemap.xml path. Locally, I'm not sure where I should be looking for these sitemap files in the dist folder. I don't see any .XML file in .nuxt or /.nuxt/dist folders after building locally, yet it still works. I'm confused why it's not building or working online but does so locally.

Thanks in advance for your help!!!!

The relevant part of my nuxt.config.js file is:

modules: [
    '@nuxtjs/axios',
    '@nuxtjs/redirect-module',
    '@nuxtjs/sitemap',
    'nuxt-i18n',
    'nuxt-webfontloader',
],

sitemap: {
    sitemaps: [
      {
        routes() {
          return getAppRoutes()
        },
        path: 'main-sitemap.xml',
      },
      {
        routes() {
          return getCounterRoutes('')
        },
        path: 'counter-sitemap1.xml',
      },
      {
        routes() {
          return getCounterRoutes('/es')
        },
        path: 'counter-sitemap2.xml',
      },
      {
        routes() {
          return getCounterRoutes('/fr')
        },
        path: 'counter-sitemap3.xml',
      },
      {
        routes() {
          return getCounterRoutes('/cn')
        },
        path: 'counter-sitemap4.xml',
      },
      {
        routes() {
          return getCounterRoutes('/kr')
        },
        path: 'counter-sitemap5.xml',
      },
      {
        routes() {
          return getCounterRoutes('/ru')
        },
        path: 'counter-sitemap6.xml',
      },
      {
        routes: [],
        path: '/blog/post-sitemap.xml',
      },
      {
        routes: [],
        path: '/blog/page-sitemap.xml',
      },
      {
        routes: [],
        path: '/blog/news-sitemap.xml',
      },
      {
        routes: [],
        path: '/blog/category-sitemap.xml',
      },
      {
        routes: [],
        path: '/blog/post_tag-sitemap.xml',
      },
    ],
    path: '/sitemap.xml',
  },
}

**Comment by cam424** [comment] 2020-11-14 18:20
Seconding this report. I've got a nuxt app being served in ssr mode and when built for production (nuxt build + nuxt start) the sitemap route fails to the error page, despite working in dev mode. I'm using nuxt's native routing and not customizing our that behavior in any way.

That being said, our temporary fix for anyone else who is struggling has been to go to the sitemap page while in dev mode, copying the contents, adding a sitemap.xml file to the static folder and pasting the contents there. It's a bit of a run around but it's holding us over until this is resolved or we find an alternative dynamically generated method.

**Comment by NicoPennec** [comment] 2020-11-15 11:02
@Thyoity @febrihidayan @larswww @cam424  Thanks for your reports 

Could you give me more details about your deployment process and your host provider? 🙏

**Comment by cam424** [comment] 2020-11-15 19:44
@NicoPennec We deploy a dockerfile via bitbucket => codebuild => codepipeline to AWS ecs, with domain managed in route 53.

**Comment by JSAustin** [comment] 2020-11-15 20:19
Hello, I experienced issues with deploying via CodeBuild on AWS and managed to fix it. The issue I had was that I was not correctly including all files, including nuxt.config in the build artifact, so it would build fine, but then it used the default nuxt.config settings because it didn't include one to be used by npm start. You may want to verify that you are including that in your build artifact and any other necessary files for this.

In case it helps, here is the updated artifacts section of my buildspec. You can see I had to add the 'nuxt.config.js' to get it to work.

```
artifacts:
    files:
        - '.ebextensions/**/*'
        - '.platform/**/*'
        - '.nuxt/dist/**/*'
        - 'package.json'
        - 'nuxt.config.js'
        - '.npmrc'
        - 'static/**/*'
        - 'utils/**/*'
        - 'components/**/*'
        - 'pages/**/*'
        - 'layouts/**/*'
        - 'services/**/*'
        - 'store/**/*'
        - 'locales/**/*'
        - 'assets/**/*'
        - 'middleware/**/*'
        - 'plugins/**/*'
```

**Comment by NicoPennec** [comment] 2020-11-15 20:37
On Vercel (formerly called Zeit Now) for eg., there is a know deploy issue.
The Vercel deploy script doesn't copy all files... It's not an issue from the sitemap-module.
See the right way to set the deploy config here: https://github.com/nuxt-community/sitemap-module/issues/106#issuecomment-603533758

**Comment by NicoPennec** [comment] 2020-11-15 20:42
@cam424 take a look to this dockerfile config tip: https://github.com/nuxt-community/sitemap-module/issues/18#issuecomment-642448547

**Comment by luokunman** [comment] 2020-11-19 10:54
I'm having the same issue.In local, everything is working fine, but in production, the sitemap.xml is unreachable, 404 error.
配置nuxt.config.js如下
![image](https://user-images.githubusercontent.com/41885648/99657093-a9607a80-2a98-11eb-9760-e3837e226d2d.png)

**Comment by luokunman** [comment] 2020-11-19 10:56
I'm having the same issue.In local, everything is working fine, but in production, the sitemap.xml is unreachable, 404 error.
nuxt.config.js:
`
sitemap: {
    // options
    path: '/sitemap.xml', // sitemap文件名
    hostname: 'https://www.test.com/', // 网址
    cacheTime: 1000 * 60 * 60 * 24, // 更新频率，只在 generate: false有用
    gzip: true, // 生成 .xml.gz 压缩的 sitemap
    // 排除不要页面
    exclude: [
      '/404'
    ],
    // 页面路由
    routes (callback) {
      axios.all([
        // 文章列表
        axios.get('https://api', {
          data: { progress: false }
        }),
        // 模板详情
        axios.get('https://api', {
          data: { progress: false }
        })

      ]).then(axios.spread(function (menu, fileInfo) {
        let now = new Date();
        now.setHours(now.getHours(), now.getMinutes() - now.getTimezoneOffset());
        let indexRoutes = [
          {
            url: '/',
            changefreq: 'daily',
            priority: 1,
            lastmodISO: now.toISOString()
          }
        ]
        let menuRoutes = menu.data.result.map((data) => {
          return {
            url: `/ClassificationTemplate/${data.id}`,
            changefreq: 'monthly',
            priority: 0.8
            // lastmodISO: data.post_modified
          }
        });
        let fileInfoRouter = fileInfo.data.result.map((data) => {
          return {
            url: `/ClassificationTemplate/details/${data.id}?classId=${data.cate2_id}`,
            changefreq: 'daily',
            priority: 0.6,
            lastmodISO: data.update_time
          }
        });
        // 用 concat 進行合併
        callback(null, indexRoutes.concat(menuRoutes, fileInfoRouter));
      }), function (err) {
        throw (err);
      });
    }
  }
`

**Comment by NicoPennec** [comment] 2020-11-19 14:52
@luokunman it's probably an issue on your deploy process.
As explain [here](https://github.com/nuxt-community/sitemap-module/issues/163#issuecomment-727551827), I really need more details about your deploy methodology and host provider.

**Comment by luokunman** [comment] 2020-11-20 02:03
> @luokunman it's probably an issue on your deploy process.
> As explain [here](https://github.com/nuxt-community/sitemap-module/issues/163#issuecomment-727551827), I really need more details about your deploy methodology and host provider.

I used SSR mode.
`npm run build`
`npm run start`
using pm2 deploy nuxt projuect

hostname: [https://www.jiangyuanwang.com](url)

I try `Hellow world` deploy project. can't realize sitemap

**Comment by cam424** [comment] 2020-11-20 02:17
@NicoPennec thanks, that was it! This was also the case for our static images like favicon and other meta image assets. We ultimately moved those out to s3, but while testing, copying over the static folder in the same way also resolved the issue once build and run with docker.

**Comment by luokunman** [comment] 2020-11-20 03:21
> @NicoPennec thanks, that was it! This was also the case for our static images like favicon and other meta image assets. We ultimately moved those out to s3, but while testing, copying over the static folder in the same way also resolved the issue once build and run with docker.

hey~  
have you finished the sitemap?

**Comment by cam424** [comment] 2020-11-20 03:32
> > @NicoPennec thanks, that was it! This was also the case for our static images like favicon and other meta image assets. We ultimately moved those out to s3, but while testing, copying over the static folder in the same way also resolved the issue once build and run with docker.
> 
> hey~
> have you finished the sitemap?

Yeah, we are running our site in ssr mode and got it working by adjusting out dockerfile to copy in nuxt.config.js along with copying the app into the working directory. It seemed redundant but it did the trick.

**Comment by luokunman** [comment] 2020-11-20 03:38
> > > @NicoPennec谢谢，就是这样！对于我们的静态图像，例如收藏夹图标和其他元图像资产，也是如此。我们最终将它们移至s3，但是在测试时，以相同的方式复制静态文件夹也解决了使用docker构建并运行后的问题。
> > 
> > 
> > 嘿〜
> > 您完成了站点地图吗？
> 
> 是的，我们正在以ssr模式运行我们的网站，并通过调整dockerfile使其复制到nuxt.config.js以及将应用程序复制到工作目录来使其正常运行。似乎多余，但却成功了。

oh thanks!
Can you give me some advice.
After trying all kinds of ways I always fail.

**Comment by cam424** [comment] 2020-11-20 03:42
I'm not sure if we are encountering the same issue. What's your deployment process?

**Comment by luokunman** [comment] 2020-11-20 05:43
> I'm not sure if we are encountering the same issue. What's your deployment process?

As mentioned above
`npm run build`
`npm run start`
using pm2 deploy nuxt projuect

did not use dockerfile

I just find sitemap-routes.json in the `.nuxt` dir

**Comment by NicoPennec** [comment] 2020-11-20 09:02
@cam424 Thanks for your feedback! Glad to know it works for you now.

@luokunman 
Can you check your server logs (access & errors logs) ?
Do you use a reverse-proxy (nginx, apache, ...) on front of your PM2 ?
Then can you make a simple test : create a "test.xml" in your "static" folder, deploy it in production and try to access it on https://www.jiangyuanwang.com/test.xml

**Comment by luokunman** [comment] 2020-11-20 10:45
> @ cam424感谢您的反馈！很高兴知道它现在对您有效。
> 
> @luokunman
> 您可以检查您的服务器日志（访问和错误日​​志）吗？
> 您是否在PM2的前面使用了反向代理（nginx，apache等）？
> 然后，您可以进行一个简单的测试：在“静态”文件夹中创建“ test.xml”，将其部署到生产环境中，然后尝试通过https://www.jiangyuanwang.com/test.xml对其进行访问。[](https://www.jiangyuanwang.com/test.xml)

I tried.I can access `.xml` in the `static` folder that I created.
but 
using `@nuxtjs/sitemap`
`run build` later 
I run `run start` the packaging file locally.It's also a failure.
thanks

**Comment by NicoPennec** [comment] 2020-11-20 13:00
@luokunman I just found the following tip about PM2 + sitemap module on stackoverflow:
> Restart your PM2 server after you run npm run build. Otherwise, the /sitemap.xml will not appear.

(source: https://stackoverflow.com/questions/61042722/404-not-found-for-sitemap-xml-on-nuxt-js/64417116#64417116)

Can you try it?

**Comment by luokunman** [comment] 2020-11-23 01:47
> @luokunman I just found the following tip about PM2 + sitemap module on stackoverflow:
> 
> > Restart your PM2 server after you run npm run build. Otherwise, the /sitemap.xml will not appear.
> 
> (source: https://stackoverflow.com/questions/61042722/404-not-found-for-sitemap-xml-on-nuxt-js/64417116#64417116)
> 
> Can you try it?

I've tried, but Still failed.

**Comment by codeman-yh** [comment] 2020-11-23 07:04
I also have same problem,and i still don't know how to solve this problem.

**Comment by NicoPennec** [comment] 2020-11-23 10:43
@codeman-yh please, give all details about your deployment process and your host provider? I cannot help you if I'm blind...

**Comment by luokunman** [comment] 2020-11-24 03:21
> @luokunman I just found the following tip about PM2 + sitemap module on stackoverflow:
> 
> > Restart your PM2 server after you run npm run build. Otherwise, the /sitemap.xml will not appear.
> 
> (source: https://stackoverflow.com/questions/61042722/404-not-found-for-sitemap-xml-on-nuxt-js/64417116#64417116)
> 
> Can you try it?

Is the version incompatible?
I find the old projects work.
now version:
`    
    "nuxt": "^2.13.3",
    "nuxt-property-decorator": "^2.7.2",
    "@nuxtjs/sitemap": "^2.4.0",
`

old version: 
`"@nuxtjs/sitemap": "^0.1.1",
"nuxt": "^1.0.0",`

**Comment by luokunman** [comment] 2020-11-24 04:03
> @luokunman I just found the following tip about PM2 + sitemap module on stackoverflow:
> 
> > Restart your PM2 server after you run npm run build. Otherwise, the /sitemap.xml will not appear.
> 
> (source: https://stackoverflow.com/questions/61042722/404-not-found-for-sitemap-xml-on-nuxt-js/64417116#64417116)
> 
> Can you try it?

I see a problem. I'm terribly sorry. The reason is that I didn't put the `nuxt.config.js` in the root directory.
I'm such a fool.
thanks!!  star!!!

**Comment by NicoPennec** [comment] 2020-11-24 08:21
@luokunman cool, thanks! I'm happy to hear that you have solved your problem 👍

**Comment by aner87** [comment] 2020-12-20 00:31
Hello everybody,

I have the same issue, and I am using Google's Cloud Functions as deploying end.
I think the reason it's not working might be due to the fact that my script is not copying the sitemap file over to the static assets folder.
Problem is, I have no idea how to do it (not even manually) because I don't know how to find it: after I run `npm run build` , where is it supposed to be located?

Thanks

**Comment by UnderTheMoonspell** [comment] 2021-01-05 19:21
I am having the same problem but in local.

✔ Generated /sitemap.xml -> i get this log, but then i get 404 and I also only see a sitemap-routes.json in .nuxt/dist (created after nuxt build), no other signs of a sitemap.xml

`  sitemap: {
    path: './sitemap.xml',
    hostname: process.env.HOSTNAME
  },`

**Comment by UnderTheMoonspell** [comment] 2021-01-05 19:55
For me to get the sitemap.xml created I have to manually call nuxt generate inside my run script. Then a dist folder is created and the sitemap.xml will be inside (we then copy it to our statics folder).

Why is the sitemap created only on nuxt generate?

**Comment by NicoPennec** [comment] 2021-01-05 20:05
@UnderTheMoonspell
on SSR mode, the sitemap is dynamically created and served by the server, as any Nuxt Page.
on Generate mode, the sitemap is writing once and then copying into the `dist` folder. You shouldn't need to copy your `sitemap.xml` file to static, the module does that for you.

**Comment by NicoPennec** [comment] 2021-01-05 20:07
@aner87 can you give the full process to reproduce your issue step by step? (eg. nuxt mode, commands run, sitemap config, deploy script, docker config, ...)

**Comment by UnderTheMoonspell** [comment] 2021-01-05 20:10
@NicoPennec tks for the reply.

 I tried running nuxt build and then nuxt or nuxt start and I always get 404. Also I don't see the "Generated ./sitemap.xml" log that I see when I run nuxt generate

**Comment by NicoPennec** [comment] 2021-01-05 20:20
@UnderTheMoonspell can you give me more details, please.
You have  404 on localhost ? on production ? which cloud provider ?

**Comment by UnderTheMoonspell** [comment] 2021-01-05 20:34
On local, just running nuxt dev script. I also tried with nuxt build + nuxt start, also same. Can only have the sitemap generator by running our custom start process which calls nuxt generate before running nuxt start

**Comment by NicoPennec** [comment] 2021-01-05 20:41
@UnderTheMoonspell  Please share your `sitemap` configuration, from your `nuxt.config.js` file. I can't help you without details.

**nb:** the log "_Generated ./sitemap.xml_" is only for the **generated** mode, but not for **ssr**. Because on SSR the xml file is not generated, but served by Nuxt.

**Comment by UnderTheMoonspell** [comment] 2021-01-05 20:50
`  sitemap: {
    path: './sitemap.xml',
    hostname: process.env.DOMAIN,
    // exclude: () => require('./sitemap').getNonIndexablePages(),
    // routes: () => require('./sitemap').getRoutes()
  },`
  
 I just have this. I dumbed it down for my tests to see if it was something related to those functions but apparently not

**Comment by NicoPennec** [comment] 2021-01-05 20:54
@UnderTheMoonspell your path is wrong `path: './sitemap.xml',` => `path: '/sitemap.xml',`

or just remove this `path` option, because you use the [default value](https://sitemap.nuxtjs.org/usage/sitemap-options#path-optional---string).

**Comment by UnderTheMoonspell** [comment] 2021-01-05 21:06
Yeap it worked! At some point I did remove it but aparently didnt go through my tests to see if it was working. Thanks!

**Comment by mckrava** [comment] 2021-01-10 22:59
I hope it will help smb.

I had the same problem and very custom project's folders structure. App was deployed to AWS EBS from Bitbucket and Bitbucket Pipelines. Reason of 404 error to `/sitemap.xml` route on prod was missed `nuxt.config.js` file in root folder already in EC2 instance. I didn't add `nuxt.config.js` to artifacts in pipeline and it wasn't copied to the prod instance. In other words - `nuxt.config.js` must be near compiled `.nuxt` folder on the server. Somehow it was not clear for me )))

**Comment by alfaben12** [comment] 2021-01-19 10:03
> Hi @larswww, Is your server.js code the same as mine? I used it like this and it worked
> 
> ```js
> const { loadNuxt } = require('nuxt')
> const server = require("express")()
> 
> async function start() {
> 
>     // We get Nuxt instance
>     const nuxt = await loadNuxt('start')
> 
>     // Render every route with Nuxt.js
>     server.use(nuxt.render)
>     
>     // Listen the server
>     server.listen()
> 
> }
> 
> start()
> ```

I also use this code for run nuxt start, but when access domain.com/sitemap.xml still 404

**Comment by NicoPennec** [comment] 2021-01-19 10:19
Hi @alfaben12,

Can you share project source code to reproduce?
Have you copy and load your `nuxt.config.js` file with your server?

**Comment by alfaben12** [comment] 2021-01-19 15:48
Hi @NicoPennec 

My nuxt.config.js
mode: universal
ssr: true

And my solution is:
1. nuxt generate 
2. copy sitemap.xml results from /dist to /static folder 
3. nuxt build 

and you can access your sitemap.xml correctly. 
ex: domain.com/sitemap.xml

is there something wrong with my way?

**Comment by NicoPennec** [comment] 2021-01-19 16:00
@alfaben12,  your solution is not the right way... the sitemap module works fine with the universal mode.

On localhost, it works ?
How did you deploy on production (with docker ? a specific process to a specific cloud provider ?).
You really must give more details to request help (for eg, it seems you works with an express + nuxt instead of the default nuxt template)

**Comment by alfaben12** [comment] 2021-01-20 04:27
@NicoPennec on localhost same not work like in production, cannot access localhost:port/sitemap.xml
my nuxt.config.js
https://gist.github.com/alfaben12/b5b97c2bc30d3315d12ed879bfa1eb4a

I am work with nuxtjs only for web development, and run nuxt start with express js

**Comment by NicoPennec** [comment] 2021-01-20 08:26
@alfaben12 thanks for the gist file.

First problem, the sitemap-module is a server middleware, so in your `nuxt.config.js` move declaration at the end of your `modules` array instead of the `buildModules` as specified in the [setup docs](https://sitemap.nuxtjs.org/guide/setup#setup).

Then, I have tried your sitemap config on a new nuxt project create from the scratch (with the official [nuxt-create-app](https://nuxtjs.org/docs/2.x/get-started/installation#using-create-nuxt-app)) and it works perfectly, see my screenshot:

<img width="501" alt="sitemap" src="https://user-images.githubusercontent.com/493223/105147250-38bdf480-5b01-11eb-918d-939ccbcadd19.png">

So the issue comes from your side, probably your nuxt setup with express.js is wrong 🤔

**Comment by alfaben12** [comment] 2021-01-20 12:03
@NicoPennec thanks domain.com/sitemap.xml is work now. It's my bad for putting what should be in `modules` not in `buildModules`

**Closed as completed** 2021-03-03 20:43 UTC
Labels: question

**Comment by danieldanielecki** [comment] 2023-03-07 09:25
In case of someone using `npm run build`, it might help: https://github.com/nuxt-community/sitemap-module/issues/227#issuecomment-1457831769
